package com.mita.wanandroid.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mita.wanandroid.dao.UserCollection;

import com.mita.wanandroid.dao.UserCollectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userCollectionDaoConfig;

    private final UserCollectionDao userCollectionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userCollectionDaoConfig = daoConfigMap.get(UserCollectionDao.class).clone();
        userCollectionDaoConfig.initIdentityScope(type);

        userCollectionDao = new UserCollectionDao(userCollectionDaoConfig, this);

        registerDao(UserCollection.class, userCollectionDao);
    }
    
    public void clear() {
        userCollectionDaoConfig.clearIdentityScope();
    }

    public UserCollectionDao getUserCollectionDao() {
        return userCollectionDao;
    }

}
